---
- debug:
    msg: Install custom vimrc setup

- name: Added required packages for this vimrc
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - cmake
    - build-essential
    - tmux
    - git
    - python3-dev
    - inotify-tools
  tags:
    - vim
    - vimrc

- name: Install vimrc
  ignore_errors: True
  git:
    repo: "{{ vimrc_repo }}"
    dest: "~/.vim"
  tags:
    - vim
    - vimrc

- name: Create a softlink to the .vimrc file
  file:
    src: ~/.vim/.vimrc
    dest: ~/.vimrc
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  tags:
    - vim
    - vimrc

- name: Create a softlink to the snippets directory
  file:
    src: ~/.vim/snippets
    dest: ~/snippets
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  tags:
    - vim
    - vimrc


- name: Get the home path for root
  become: true
  shell: |
    cat /etc/passwd | grep root | awk 'BEGIN {FS=":"}; {print $6}'
  register: root_path
  tags:
    - vim
    - vimrc

- name: Create a softlink to the snippets directory for the root user
  become: yes
  file:
    src: "/home/{{ user }}/.vim/snippets"
    dest: "{{ root_path.stdout }}/snippets"
    state: link
  tags:
    - vim
    - vimrc

- name: Create a softlink to the .vim directory for the root user
  become: yes
  file:
    src: "/home/{{ user }}/.vim"
    dest: "{{ root_path.stdout }}/.vim"
    state: link
  tags:
    - vim
    - vimrc

- name: Create a softlink to the .vimrc file for the root user
  become: yes
  file:
    src: "/home/{{ user }}/.vim/.vimrc"
    dest: "{{ root_path.stdout }}/.vimrc"
    state: link
  tags:
    - vim
    - vimrc

- name: Create a softlink to the .pdbrc file for the root user
  become: yes
  file:
    src: "/home/{{ user }}/.vim/.pdbrc"
    dest: "{{ root_path.stdout }}/.pdbrc"
    state: link
  tags:
    - vim
    - vimrc

- name: Check if YouCompleteMe directory exists
  stat:
    path: "/home/{{ user }}/.vim/plugged/YouCompleteMe"
  register: ycm


# This will install all of the required vim plugins
- name: Have plugged plugin pull down all required vim packages
  shell: "vim +PlugInstall +qall"
  # Thank you to Eddie Staniloiu for this help
  args:
    stdin: "\n"
  tags:
    - vim
    - vimrc

# This will make text auto-completion run on the computer in vim
- name: Make text auto-completion package for vim
  shell: "python3 ./install.py"
  args:
    chdir: "~/.vim/plugged/YouCompleteMe"
  when: ycm.stat.exists == False
  ignore_errors: yes
  tags:
    - vim
    - vimrc
