---
- debug:
    msg: Install custom vimrc setup

- name: Added required packages for this vimrc
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - cmake
    - build-essential
    - tmux
    - git
    - python-dev
    - python3-dev
    - inotify-tools
  tags:
    - vim

- name: Install vimrc
  ignore_errors: True
  git:
    repo: "{{ vimrc_repo }}"
    dest: "~/.vim"
  tags:
    - vim

# This is a mix of vim and tmux and pdb
- name: Softlink dot files
  shell: "{{ item }}"
  loop:
    - "ln -s ~/.vim/.vimrc ~/.vimrc"
    - "ln -s ~/.vim/snippets ~/snippets"
    - "ln -s ~/.vim/.pdbrc ~/.pdbrc"
    - "ln -s ~/.vim/.pdbrc.py ~/.pdbrc.py"
  ignore_errors: True
  args:
    chdir: "~"
  tags:
    - vim


- name: Create a softlink to the .vimrc file
  file:
    src: ~/.vim/.vimrc
    dest: ~/.vimrc
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  tags:
    - vim

- name: Create a softlink to the snippets directory
  file:
    src: ~/.vim/snippets
    dest: ~/snippets
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  tags:
    - vim

- name: Create a softlink to the .pdbrc file
  file:
    src: ~/.vim/.pdbrc
    dest: ~/.pdbrc
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  tags:
    - vim

- name: Create a softlink to the .pdbrc.py file
  file:
    src: ~/.vim/.pdbrc.py
    dest: ~/.pdbrc.py
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  tags:
    - vim

- name: Get the home path for root
  become: true
  shell: |
    cat /etc/passwd | grep root | awk 'BEGIN {FS=":"}; {print $6}'
  register: root_path
  tags:
    - vim

- name: Create a softlink to the snippets directory for the root user
  become: yes
  file:
    src: "/home/{{ user }}/.vim/snippets"
    dest: "{{ root_path.stdout }}/snippets"
    state: link
  tags:
    - vim

- name: Create a softlink to the .vimrc file for the root user
  become: yes
  file:
    src: "/home/{{ user }}/.vim/.vimrc"
    dest: "{{ root_path.stdout }}/.tmux.conf"
    state: link
  tags:
    - vim

- name: Create a softlink to the .pdbrc file for the root user
  become: yes
  file:
    src: "/home/{{ user }}/.vim/.pdbrc"
    dest: "{{ root_path.stdout }}/.pdbrc"
    state: link
  tags:
    - vim

# This will install all of the required vim plugins
- name: Have plugged plugin pull down all required vim packages
  shell: "vim +PlugInstall +qall"
  # Thank you to Eddie Staniloiu for this help
  args:
    stdin: "\n"
  tags:
    - vim

# This will make text auto-completion run on the computer in vim
- name: Make text auto-completion package for vim
  shell: "python3 ./install.py"
  args:
    chdir: "~/.vim/plugged/YouCompleteMe"
  tags:
    - vim

